package com.rajankumar.encyclopaedia.feature.notebook

import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.rajankumar.encyclopaedia.data.local.*
import java.util.UUID
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import org.json.JSONArray
import org.json.JSONObject

private data class NotebookHistoryAction(val stroke: NotebookStrokeEntity, val added: Boolean)
private val penColors = listOf(0xFF111111, 0xFF1D4ED8, 0xFFB91C1C, 0xFF15803D)

@Composable
fun NotebookScreen() {
  val dao=EncyclopaediaDatabase.get(LocalContext.current).dao();val scope=rememberCoroutineScope();val pages by dao.observeNotebookPages().collectAsStateWithLifecycle(emptyList())
  var title by remember{mutableStateOf("")};var pageToDelete by remember{mutableStateOf<NotebookPageEntity?>(null)};var selectedPageId by remember{mutableStateOf<String?>(null)};var renamePage by remember{mutableStateOf<NotebookPageEntity?>(null)};var renameText by remember{mutableStateOf("")}
  pageToDelete?.let{p->AlertDialog(onDismissRequest={pageToDelete=null},title={Text("Delete notebook page?")},text={Text("${p.title} and every layer and handwritten stroke on it will be permanently deleted.")},confirmButton={TextButton(onClick={pageToDelete=null;scope.launch(Dispatchers.IO){dao.deleteNotebookPage(p.id)}}){Text("Delete")}},dismissButton={TextButton(onClick={pageToDelete=null}){Text("Cancel")}})}
  renamePage?.let{p->AlertDialog(onDismissRequest={renamePage=null},title={Text("Rename page")},text={OutlinedTextField(renameText,{renameText=it.take(100)},singleLine=true,label={Text("Page title")})},confirmButton={TextButton(enabled=renameText.isNotBlank(),onClick={val n=renameText.trim();renamePage=null;scope.launch(Dispatchers.IO){dao.renameNotebookPage(p.id,n)}}){Text("Save")}},dismissButton={TextButton(onClick={renamePage=null}){Text("Cancel")}})}
  val selectedPage=pages.firstOrNull{it.id==selectedPageId};if(selectedPage!=null){NotebookPageCanvas(selectedPage){selectedPageId=null};return}
  LazyColumn(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){
    item{Text("Notebook",style=MaterialTheme.typography.headlineMedium);Text("Handwritten study pages are stored locally and included in your backups.",color=MaterialTheme.colorScheme.onSurfaceVariant)}
    item{Card(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("New page",style=MaterialTheme.typography.titleMedium);OutlinedTextField(title,{title=it.take(100)},label={Text("Page title")},modifier=Modifier.fillMaxWidth(),singleLine=true);Button(enabled=title.isNotBlank(),onClick={val t=title.trim();title="";scope.launch(Dispatchers.IO){val id=UUID.randomUUID().toString();dao.upsertNotebookPage(NotebookPageEntity(id=id,title=t));dao.upsertNotebookLayer(NotebookLayerEntity(id=UUID.randomUUID().toString(),pageId=id,name="Writing"))}}){Text("Create page")}}}}
    if(pages.isEmpty())item{Text("No notebook pages yet. Create one above to start writing.")}else items(pages,key={it.id}){p->Card(Modifier.fillMaxWidth().clickable{selectedPageId=p.id}){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(p.title,style=MaterialTheme.typography.titleMedium);Text(p.background.lowercase().replaceFirstChar{it.uppercase()}+" page",color=MaterialTheme.colorScheme.onSurfaceVariant)};Row{TextButton(onClick={renameText=p.title;renamePage=p}){Text("Rename")};TextButton(onClick={pageToDelete=p}){Text("Delete",color=MaterialTheme.colorScheme.error)}}}}}
  }
}

@Composable
private fun NotebookPageCanvas(page:NotebookPageEntity,onBack:()->Unit){
  val context=LocalContext.current;val dao=EncyclopaediaDatabase.get(context).dao();val prefs=remember(context){NotebookPreferences(context)};val scope=rememberCoroutineScope();val layers by dao.observeNotebookLayers(page.id).collectAsStateWithLifecycle(emptyList());val pageStrokes by dao.observeNotebookPageStrokes(page.id).collectAsStateWithLifecycle(emptyList())
  var selectedLayerId by remember{mutableStateOf<String?>(null)};val selectedLayer=layers.firstOrNull{it.id==selectedLayerId}?:layers.firstOrNull{it.isVisible&&!it.isLocked};val writableLayer=selectedLayer?.takeIf{it.isVisible&&!it.isLocked}
  var palm by remember{mutableStateOf(prefs.palmRejection)};var tool by remember{mutableStateOf(NotebookTool.PEN)};var penWidth by remember{mutableStateOf(prefs.penWidth)};var penColor by remember{mutableStateOf(prefs.penColorArgb)};var newLayer by remember{mutableStateOf("")};var deleteLayer by remember{mutableStateOf<NotebookLayerEntity?>(null)};var showLayers by remember{mutableStateOf(false)};var renameLayer by remember{mutableStateOf<NotebookLayerEntity?>(null)};var renameLayerText by remember{mutableStateOf("")}
  val background=runCatching{NotebookBackground.valueOf(page.background)}.getOrDefault(NotebookBackground.PLAIN);val undo=remember{mutableStateListOf<NotebookHistoryAction>()};val redo=remember{mutableStateListOf<NotebookHistoryAction>()};val visibleIds=remember(layers){layers.filter{it.isVisible}.map{it.id}.toSet()};val decoded=remember(pageStrokes){pageStrokes.mapNotNull{e->decodeStroke(e)?.let{e to it}}};val canvas=remember(decoded,visibleIds){decoded.filter{it.first.layerId in visibleIds}.map{it.second}};val selected=remember(decoded,selectedLayer?.id){decoded.filter{it.first.layerId==selectedLayer?.id}}
  deleteLayer?.let{l->AlertDialog(onDismissRequest={deleteLayer=null},title={Text("Delete layer?")},text={Text("${l.name} and every stroke on it will be permanently deleted.")},confirmButton={TextButton(onClick={deleteLayer=null;undo.clear();redo.clear();scope.launch(Dispatchers.IO){dao.deleteNotebookLayer(l.id)}}){Text("Delete")}},dismissButton={TextButton(onClick={deleteLayer=null}){Text("Cancel")}})}
  renameLayer?.let{l->AlertDialog(onDismissRequest={renameLayer=null},title={Text("Rename layer")},text={OutlinedTextField(renameLayerText,{renameLayerText=it.take(40)},singleLine=true,label={Text("Layer name")})},confirmButton={TextButton(enabled=renameLayerText.isNotBlank(),onClick={val n=renameLayerText.trim();renameLayer=null;scope.launch(Dispatchers.IO){dao.renameNotebookLayer(l.id,n)}}){Text("Save")}},dismissButton={TextButton(onClick={renameLayer=null}){Text("Cancel")}})}
  fun moveLayer(index:Int,direction:Int){val target=index+direction;if(target !in layers.indices)return;val a=layers[index];val b=layers[target];scope.launch(Dispatchers.IO){dao.setNotebookLayerSortOrder(a.id,b.sortOrder);dao.setNotebookLayerSortOrder(b.id,a.sortOrder)}}
  Column(Modifier.fillMaxSize().padding(horizontal=16.dp,vertical=10.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){
    Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Row{TextButton(onClick=onBack){Text("← Pages")};Text(page.title,style=MaterialTheme.typography.titleLarge,modifier=Modifier.padding(top=10.dp))};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){TextButton(onClick={showLayers=!showLayers}){Text(if(showLayers)"Hide layers" else "Layers (${layers.size})")};Text("Palm",modifier=Modifier.padding(top=12.dp));Switch(palm,{palm=it;prefs.palmRejection=it})}}
    Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(tool==NotebookTool.PEN,{tool=NotebookTool.PEN},label={Text("Pen")});FilterChip(tool==NotebookTool.ERASER,{tool=NotebookTool.ERASER},label={Text("Eraser")});listOf(2.5f,4f,7f).forEach{w->FilterChip(penWidth==w,{penWidth=w;prefs.penWidth=w},label={Text(if(w<3)"Fine" else if(w<6)"Medium" else "Bold")})};penColors.forEachIndexed{i,c->FilterChip(penColor==c,{penColor=c;prefs.penColorArgb=c},label={Text(listOf("Black","Blue","Red","Green")[i])})};OutlinedButton(enabled=undo.isNotEmpty(),onClick={val a=undo.removeLastOrNull()?:return@OutlinedButton;redo.add(a);scope.launch(Dispatchers.IO){if(a.added)dao.deleteNotebookStroke(a.stroke.id)else dao.upsertNotebookStroke(a.stroke)}}){Text("Undo")};OutlinedButton(enabled=redo.isNotEmpty(),onClick={val a=redo.removeLastOrNull()?:return@OutlinedButton;undo.add(a);scope.launch(Dispatchers.IO){if(a.added)dao.upsertNotebookStroke(a.stroke)else dao.deleteNotebookStroke(a.stroke.id)}}){Text("Redo")};NotebookBackground.entries.forEach{b->FilterChip(background==b,{scope.launch(Dispatchers.IO){dao.setNotebookPageBackground(page.id,b.name)}},label={Text(b.name.lowercase().replaceFirstChar{it.uppercase()})})}}
    if(showLayers)Card(Modifier.fillMaxWidth()){Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Layers",style=MaterialTheme.typography.titleSmall);Text(selectedLayer?.name?.let{"Active: $it"}?:"No writable layer",color=MaterialTheme.colorScheme.onSurfaceVariant)};layers.forEachIndexed{i,l->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){FilterChip(selectedLayer?.id==l.id,{selectedLayerId=l.id;undo.clear();redo.clear()},label={Text(l.name)});Row{TextButton(enabled=i>0,onClick={moveLayer(i,-1)}){Text("↑")};TextButton(enabled=i<layers.lastIndex,onClick={moveLayer(i,1)}){Text("↓")};TextButton(onClick={renameLayerText=l.name;renameLayer=l}){Text("Rename")};TextButton(onClick={scope.launch(Dispatchers.IO){dao.setNotebookLayerVisible(l.id,!l.isVisible)}}){Text(if(l.isVisible)"Hide" else "Show")};TextButton(onClick={scope.launch(Dispatchers.IO){dao.setNotebookLayerLocked(l.id,!l.isLocked)}}){Text(if(l.isLocked)"Unlock" else "Lock")};if(layers.size>1)TextButton(onClick={deleteLayer=l}){Text("Delete",color=MaterialTheme.colorScheme.error)}}}};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(newLayer,{newLayer=it.take(40)},label={Text("New layer")},singleLine=true,modifier=Modifier.weight(1f));Button(enabled=newLayer.isNotBlank(),onClick={val n=newLayer.trim();newLayer="";val id=UUID.randomUUID().toString();val next=(layers.maxOfOrNull{it.sortOrder}?:-1)+1;scope.launch(Dispatchers.IO){dao.upsertNotebookLayer(NotebookLayerEntity(id=id,pageId=page.id,name=n,sortOrder=next))};selectedLayerId=id;undo.clear();redo.clear()}){Text("Add")}}}}
    Card(Modifier.fillMaxWidth().weight(1f)){NotebookCanvas(strokes=canvas,palmRejection=palm,selectedTool=tool,penWidth=penWidth,penColorArgb=penColor,background=background,onStrokeFinished={s->val l=writableLayer?:return@NotebookCanvas;val e=NotebookStrokeEntity(id=UUID.randomUUID().toString(),layerId=l.id,pointsJson=encodePoints(s),width=s.width,tool=s.tool.name,colorArgb=s.colorArgb);undo.add(NotebookHistoryAction(e,true));redo.clear();scope.launch(Dispatchers.IO){dao.upsertNotebookStroke(e)}},onEraseAt={p->writableLayer?:return@NotebookCanvas;val hit=selected.lastOrNull{(_,s)->s.isNear(p)}?.first;if(hit!=null){undo.add(NotebookHistoryAction(hit,false));redo.clear();scope.launch(Dispatchers.IO){dao.deleteNotebookStroke(hit.id)}}},modifier=Modifier.fillMaxSize())}
    if(writableLayer==null)Text("Selected layer is hidden or locked. Choose a visible unlocked layer to write.",color=MaterialTheme.colorScheme.onSurfaceVariant)
  }
}
private fun encodePoints(s:CanvasStroke)=JSONArray().apply{s.points.forEach{put(JSONObject().put("x",it.x.toDouble()).put("y",it.y.toDouble()))}}.toString()
private fun decodeStroke(e:NotebookStrokeEntity):CanvasStroke?=runCatching{val a=JSONArray(e.pointsJson);val p=(0 until a.length()).map{i->val o=a.getJSONObject(i);Offset(o.getDouble("x").toFloat(),o.getDouble("y").toFloat())};CanvasStroke(p,e.width,runCatching{NotebookTool.valueOf(e.tool)}.getOrDefault(NotebookTool.PEN),e.colorArgb)}.getOrNull()
